%% driveline_params.m
% Runs parameters.m and re-groups the driveline-relevant variables into a
% single "driveline" struct (motor/inverter/battery/chain/diff/halfshaft/
% wheel/vehicle). Defines no values itself -- everything traces back to
% parameters.m.

% Find parameters.m relative to THIS file's own folder, not the current
% working directory, so it works no matter where you run it from.
% Expected layout: <project root>/parameters.m, <project root>/Driveline/driveline_params.m
this_dir = fileparts(mfilename('fullpath'));
params_path = fullfile(fileparts(this_dir), 'parameters.m');   % one level up from this folder

if ~isfile(params_path)
    if isfile(fullfile(this_dir, 'parameters.m'))
        params_path = fullfile(this_dir, 'parameters.m');   % fallback: same folder as this file
    elseif ~isempty(which('parameters.m'))
        params_path = which('parameters.m');                % fallback: anywhere on the MATLAB path
    else
        error('driveline_params:missingParams', ...
            'Could not find parameters.m (checked %s and %s).', fileparts(this_dir), this_dir);
    end
end

run(params_path);   % loads all of parameters.m's variables into this workspace

% Confirm parameters.m actually defined everything this script needs
% (catches the case where an old/original copy of parameters.m got run
% instead of the current one).
required_vars = {'inverter_model', 'V_pack_nom', 'E_pack_kWh', 'cell_config', 'cell_type', ...
    'chain_type', 'final_drive_ratio_specsheet', 'diff_make', 'diff_eta', 'diff_bias_ratio', ...
    'halfshaft_length', 'halfshaft_material', 'halfshaft_joint', 'halfshaft_k_torsion', 'halfshaft_backlash', ...
    'm_v_no_driver', 'L', 'track_f', 'track_r', 'a', 'b', 'h_cg', ...
    'tyre_model', 'R_nom', 'T_hard_limit', 'torque_curve_rpm', 'torque_curve_Nm'};

defined_vars = who;   % who() lists this script's own workspace -- exist() inside cellfun would not
missing = required_vars(~ismember(required_vars, defined_vars));

if ~isempty(missing)
    error('driveline_params:staleParameters', ...
        ['parameters.m ran without error, but is missing %d variable(s): %s.\n', ...
         'This looks like an old copy of parameters.m -- replace it with the current version.'], ...
        numel(missing), strjoin(missing, ', '));
end

% Group into one struct, scoped to the inverter-input -> wheel-output chain
driveline.motor = struct( ...
    'variant',          winding_type, ...
    'T_pk',             T_pk, ...
    'T_cont',           T_cont, ...
    'omega_max_rpm',    omega_max_rpm, ...
    'K_T',              K_T, ...
    'I_pk',             I_pk, ...
    'I_cont',           I_cont, ...
    'V_nom',            V_mot, ...
    'J_r',              J_r, ...
    'J_r_refl',         J_r_refl, ...
    'mass',             m_m, ...
    'eta_pk',           eta_pk, ...
    'tau_m',            tau_m, ...
    'dKT_dT',           dKT_dT, ...
    'T_lim_winding',    T_lim_wind, ...
    'T_lim_rotor',      T_lim_rotor, ...
    'P_cont_cooling',   P_cont, ...
    'sensor_type',      sensor_type, ...
    'reverse_ok',       reverse_ok, ...
    'T_hard_limit',     T_hard_limit, ...
    'torque_curve_rpm', torque_curve_rpm, ...
    'torque_curve_Nm',  torque_curve_Nm);

driveline.inverter = struct( ...
    'model',            inverter_model, ...
    'P_disc_pk',        P_inv_disc_pk, ...
    'P_disc_cont',      P_inv_disc_cont, ...
    'P_DC_limit',       P_lim, ...
    'I_pk',             I_inv_pk, ...
    'I_cont',           I_inv_cont);

driveline.battery = struct( ...
    'V_nom',            V_pack_nom, ...
    'V_OC',             V_OC, ...
    'R_int',            R_int, ...
    'energy_kWh',       E_pack_kWh, ...
    'config',           cell_config, ...
    'cell',             cell_type);

driveline.chain = struct( ...
    'ratio',            i_g, ...
    'ratio_specsheet',  final_drive_ratio_specsheet, ...
    'type',             chain_type, ...
    'eta',              eta_g);

driveline.diff = struct( ...
    'make',             diff_make, ...
    'eta',              diff_eta, ...
    'bias_ratio',       diff_bias_ratio);

driveline.halfshaft = struct( ...
    'length',           halfshaft_length, ...
    'material',         halfshaft_material, ...
    'joint',            halfshaft_joint, ...
    'k_torsion',        halfshaft_k_torsion, ...
    'backlash',         halfshaft_backlash);

driveline.wheel = struct( ...
    'tyre',             tyre_model, ...
    'r_nominal',        R_nom, ...
    'r_loaded',         R_e, ...
    'J_w',              J_w);

driveline.vehicle = struct( ...
    'mass_no_driver',   m_v_no_driver, ...
    'mass_total',       m_v, ...
    'wheelbase',        L, ...
    'track_f',          track_f, ...
    'track_r',          track_r, ...
    'a',                a, ...
    'b',                b, ...
    'h_cg',             h_cg, ...
    'drive_config',     driven_axle);

disp('driveline struct assembled from parameters.m.');